export const UPDATE_SEARCH_RESULTS = 'UPDATE_SEARCH_RESULTS';
export const GET_CURRENCY_CODE = 'GET_CURRENCY_CODE';
export const SHOW_CURRENCY_DETAILS = 'SHOW_CURRENCY_DETAILS';
export const SHOW_CURRENCY_MONTHLY_DETAILS = 'SHOW_CURRENCY_MONTHLY_DETAILS';